package prueba.prolog;


import java.io.IOException;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.text.AttributeSet;
import javax.swing.text.BadLocationException;
import javax.swing.text.Element;
import javax.swing.text.StyledDocument;
import javax.swing.text.Utilities;
import static javax.swing.text.Utilities.getWordEnd;
import static javax.swing.text.Utilities.getWordStart;
import org.jpl7.Query;
import org.jpl7.Term;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Felix Guzman
 */
public class DictionaryWindow extends javax.swing.JFrame {

    private String sinonimos = "";
    private String  palabra = "";
    /**
     * Creates new form DictionaryWindow
     */
    public DictionaryWindow() {
        initComponents();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        txtField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Buscar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        txtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFieldActionPerformed(evt);
            }
        });

        jLabel1.setText("Opciones:");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sinonimos", "Antonimos" }));

        jTextPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextPane1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTextPane1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 306, Short.MAX_VALUE))
                            .addComponent(txtField)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(txtField, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 205, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFieldActionPerformed
       
      
        /* Here after getting the word from jTextPane we print the definition
        of that word in jTextArea... I got the code for this part */
        
    }//GEN-LAST:event_txtFieldActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String palabra = txtField.getText();
        jTextPane1.setText("");
        sinonimos = "";
        String[] sin = separarFrase(palabra);
        String res = "";
        if(jComboBox1.getSelectedIndex() == 0)
        {
            if(!palabra.equalsIgnoreCase(""))
            {
               for (String string : sin) {
                res += buscarSinonimo(string) + " ";
            }
               
           // res = res.replace("'", "");
            jTextPane1.setText(res); 
            }
            
        }
       
        
        
//        if(jComboBox1.getSelectedIndex() == 0)
//        {
//             String re = buscarDefinicion(palabra);
//             jTextArea1.setText(re.toString());
//        }
        
       
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextPane1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextPane1MouseClicked
         
        if(!jTextPane1.getText().equalsIgnoreCase(""))
        {
            try {
            String wrd="";
            int pt=jTextPane1.viewToModel(evt.getPoint());
            int spt=Utilities.getWordStart(jTextPane1,pt);
            int ept=Utilities.getWordEnd(jTextPane1,pt);
            jTextPane1.setSelectionStart(spt);
            jTextPane1.setSelectionEnd(ept);
            wrd=jTextPane1.getSelectedText();
          
            if(jComboBox1.getSelectedIndex()==0 && !wrd.isEmpty())
            {
               System.out.println("TextPane word="+wrd);
                palabra = "";

                String palabras = jTextPane1.getText();
                String[] sep = separarFrase(palabras);
                jTextPane1.setText("");
                wrd = wrd.replaceAll("\\s+","");

                palabra = palabras.replaceFirst(wrd, buscarSinonimo(wrd));
    //          System.out.println("Sinonimo de: " + wrd + " es: " + buscarSinonimo(wrd) );
    //          System.out.println(buscarSinonimo(wrd));

                jTextPane1.setText(palabra);
            }
//            
         
            
        } catch (BadLocationException ex) {
            Logger.getLogger(DictionaryWindow.class.getName()).log(Level.SEVERE, null, ex);
        }
        }
        
    }//GEN-LAST:event_jTextPane1MouseClicked

    /**
     * @param pal
     * @return 
     */
    
    public String buscarSinonimo(String pal)
    {
        String q = "consult('Resources/Out/sinonimos.pl').";
        Query q1 = new Query(q);
        System.out.println("Consulta de archivo" + " " + (q1.hasSolution() ?"correcto":"incorrecto" ) );
        String x1 = null;
        
        x1= pal.toLowerCase();
        x1 = x1.replace("'", "");
        System.out.println("Palabra sin '' : " + x1);
        String y = "_";
        String sinonimo = "sacarsinonimo("+x1+",X).";
         Query q2 = null;
        if(!pal.isEmpty())
        {
            q2 = new Query(sinonimo);
        }
        else
        {
            return pal;
        }
        
        Term x = null ;
        if(q2.hasSolution())
        {
      
            x = q2.oneSolution().get("X");
            sinonimos += x.toString() + " ";
        }
        else
        {
          sinonimos += pal + " ";
          x = new org.jpl7.Integer(1);
        }
       
    
       if(!x.isInteger())
       {
           return x.toString();
       }
       else
       {
           return pal;
       }
               
    }
    
    public String[] separarFrase(String s) {
        int cp = 0; // Cantidad de palabras
         
        // Recorremos en busca de espacios
        for (int i = 0; i < s.length(); i++) {
            if (s.charAt(i) == ' ') { // Si es un espacio
                cp++; // Aumentamos en uno la cantidad de palabras
            }
        }
         
        // "Este blog es genial" tiene 3 espacios y 3 + 1 palabras
        String[] partes = new String[cp + 1];
        for (int i = 0; i < partes.length; i++) {
            partes[i] = ""; // Se inicializa en "" en lugar de null (defecto)
        }
         
        int ind = 0; // Creamos un índice para las palabras
        for (int i = 0; i < s.length(); i++) {
            if (s.charAt(i) == ' ') { // Si hay un espacio
                ind++; // Pasamos a la siguiente palabra
                continue; // Próximo i
            }
            partes[ind] += s.charAt(i); // Sino, agregamos el carácter a la palabra actual
        }
        return partes; // Devolvemos las partes
    }
    
    public String buscarDefinicion(String pal)
    {
        String q = "consult('Resources/DiccionarioParcial2.pl')";
        Query q1 = new Query(q);
        String X="";
        System.out.println("Consulta de archivo" + " " + (q1.hasSolution() ?"correcto":"incorrecto" ) );
        String a = null;
        pal = pal.toLowerCase();
        String consulta = "means("+pal+",X)";
        
        Query q2 = new Query(consulta);
     
        //res = Util.atomListToStringArray(q2.oneSolution().get(res));
       Term x = q2.oneSolution().get("X");
                    
        Map<String, Term> m[];
            
       
        m = q2.allSolutions();
        
        a = x.toString();

        
        return a;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextPane jTextPane1;
    private static javax.swing.JTextField txtField;
    // End of variables declaration//GEN-END:variables
}
